export const LABELS = {
  FullName: 'Full Name',
  Duration:'Duration',
  takePhoto: 'Take Picture',
  findParkingArea: 'Find Parking Area',
  appTitle:'E-Parking Management',
  allBookings:'All Booking requests',
  step1:'Step 1 of 4',
  AreaLayoutUpdated:'The layout of your Parking area is successfully stored!',
  ParkingDashboard:'Parking Dashboard',
  selectSpot:'Select Spot',
  update:'Update',
  booked:'Booked',
  seeAll:'See all',
  updateSlotMessage: 'Select the new status for this slot',
  setSlotStatus: 'Manage Slot Availability',
  imageUploaded: 'Image Uploaded Successfully',
  top: 'Top',
  available:'Available',
  chooseFromGallery: 'Choose from Gallery',
  bottom: 'Bottom',
  horizontal: 'Horizontal',
  vertical: 'Vertical',
  center: 'Center',
  left: 'Left',
  right: 'Right',
  pricePerHour: 'Hourly rate in PKR',
  upload: 'Upload',
  uploadProfile: 'Upload Area Picture',
  enter: 'Enter',
  exit: 'Exit',
  route: '- - - - - - - - - - - - - - -',
  cardNumber: 'Card Number',
  loginSuccess: 'Login Successful',
  emailSent: 'Email is sent to your email address',
  back: 'Back',
  successfullyRegistered: 'User registered successfully',
  AllList: 'All List',
  latitudeOfArea: 'Latitude of the area',
  longitudeOfArea: 'Longitude of the area',
  spaceName: 'Name of Parking Area',
  noOfRows: 'No of Rows',
  noOfLots: 'Total Parking slots',
  spaceDetails: 'Space Details',
  accepted: 'Accepted',
  addSpace: 'Add Space',
  details: 'Details',
  rejected: 'Rejected',
  requests:'Requests',
  bookingRequests: 'Booking Requests',
  total: 'Total',
  accept: 'Accept',
  decline: 'Decline',
  jazzCash: 'Jazz Cash',
  easyPaisa: 'Easy Paisa',
  View: 'View Details',
  parkingDetails: 'Parking Details',
  parkingTimer: 'Parking Timer',
  slotID: 'Slot ID',
  extraCharges: 'Extra Charges',
  time: 'Time',
  date: 'Date',
  address: 'Address',
  price: 'Price',
  parkingArea: 'Parking area',
  confirm: 'Confirm',
  cancel: 'Cancel',
  upcoming: 'Upcoming',
  past: 'Past',
  occupied: 'Occupied',
  entryPoint: 'Entry Point',
  exitPoint: 'Exit Point',
  recentPlaces: 'Recent Places',
  popularLocations: 'Popular Parking areas',
  confirmBooking: 'Confirm Booking',
  payPal: 'PayPal',
  location: 'Location',
  stripe: 'Stripe',
  GooglePay: 'Google Pay',
  choosePayMethod: 'Choose Payment Method',
  logout: 'Logout',
  notification: 'Notifications',
  payment: 'Payment',
  personalInfo: 'Personal Information',
  profile: 'My Profile',
  feedbackPlaceholder: 'Share your thoughts and experiences here...',
  feedbackQues: 'How was your experience?',
  Feeback: 'Feedback',
  pickSpot: 'Pick Parking spot',
  Submit: '  Submit  ',
  feedbackSubHeading: 'Your feedback will help us improve our services',
  paymentSuccessMsg: 'Parking booking at parsley was successfully done',
  paymentSuccessful: 'Payment Successful',
  addFeedback: 'Add Feedback',
  VehicleName: 'Vehicle Name',
  licenseNo: 'License No',
  carModel: 'Car Model',
  VehicleDetails: 'Vehicle Details',
  didntRecieveCode: "Didn't recieve code?",
  lastName: 'Last Name',
  sendCode: 'Send OTP',
  verify: 'Verify',
  save: 'Save',
  newPass: 'New Password',
  createNewPass: 'Create New Password',
  resendCode: 'Resend code',
  resendCodein: 'Resend code in',
  createYourNewPass: 'Create New Password for your account',
  email: 'Email',
  password: 'Password',
  continue: 'Continue',
  enterEmail: 'Enter email address',
  confirmPassword: 'Confirm Password',
  login: 'Login',
  register: 'Register',
  forgotPassword: 'Forgot Password',
  title: 'E-PARKING MANAGEMENT',
  welcomeTo: 'Welcome to',
  contiueWith: 'or continue with',
  verifyEmail: 'Verify Your Email',
  user: 'User',
  vendor: 'Vendor',
  CreateAccount: 'Create your',
  loginAccount: 'Login to your',
  forgotPassDetails:
    'Please enter your email address to recieve verification code',
  account: 'Account',
  confirmPass: 'Confirm Password',
  dontHaveAccount: "Don't have an account?",
  signup: 'Sign Up',
  haveAccount: 'Already have an account?',
  signin: 'Sign in',
  phonePlaceholder: '3456999 9',
  rememberMe: 'Remember me',
  next: 'Next',
  skip: 'Skip',
  appIntro:
    'Effortless parking solutions, streamline your experience with our user-friendly E-parking management system today!',
  onBoardUserHeading1: 'Find Parking Places Around You Easily',
  onBoardUserHeading2: 'Navigate and Reserve Your Ideal Parking Spot with Ease',
  onBoardUserHeading3:
    'Experience Confidence with Secure Payments and Instant Notifications',
  onBoardUserText1:
    'Welcome to E-Parking, your go-to solution for seamless parking experiences. Find, book, and pay for parking effortlessly',
  onBoardUserText2:
    'Enjoy stress-free parking. Search, select, and book parking spaces with just a few taps. Your spot is waiting for you!',
  onBoardUserText3:
    'Securely pay for your parking within the app. Receive instant notifications for a smooth and worry-free parking experience.',
  onBoardVendorHeading1:
    'Join E-Parking Network for Business Expansion Success',
  onBoardVendorHeading2:
    'Effortlessly Showcase and Manage Your Parking Listings Here',
  onBoardVendorHeading3:
    'Unlock Maximum Revenue with Real-Time Business Analytics Insights',
  onBoardVendorText1:
    'Welcome to E-Parking Vendor onboarding. Connect with customers and maximize your parking space utilization.',
  onBoardVendorText2:
    'Easily add, update, and manage your parking listings. Showcase your spaces to users seeking convenient parking options.',
  onBoardVendorText3:
    'Access real-time analytics and receive secure payments. Maximize your revenue and enhance the efficiency of your parking business.',
};
