export const LABELS = {
  FullName: 'Full Name',
  selectDate: 'Select Date',
  selectTime: 'Select Time',
  NoBookings: 'No Bookings Yet',
  Duration: 'Duration',
  parkingCheckIn:'Parking Check in',
  takePhoto: 'Take Picture',
  noNotifications: 'No Notifications Yet',
  findParkingArea: 'Find Parking Area',
  appTitle: 'E-Parking Management',
  noBookingsYet: 'No Bookings Yet',
  directionsHeading:'Parking Instructions:',
  thanksLetter:' Thank you for choosing us! Have a smooth parking experience. 🚗🌟',
  allBookings: 'All Booking requests',
  areaName:'Area name',
  step1: 'Step 1 of 4',
  letsPark:'Lets Park',
  enterNewPrice:'Enter New Price',
  AreaLayoutUpdated: 'The layout of your Parking area is successfully stored!',
  ParkingDashboard: 'Parking Dashboard',
  selectSpot: 'Select Spot',
  update: 'Update',
  booked: 'Booked',
  seeAll: 'See all',
  updateSlotMessage: 'Select the new status for this slot',
  setSlotStatus: 'Manage Slot Availability',
  imageUploaded: 'Image Uploaded Successfully',
  top: 'Top',
  available: 'Available',
  showDirections:'Show Directions',
  chooseFromGallery: 'Choose from Gallery',
  bottom: 'Bottom',
  horizontal: 'Horizontal',
  vertical: 'Vertical',
  center: 'Center',
  left: 'Left',
  right: 'Right',
  pricePerHour: 'Hourly rate in PKR',
  upload: 'Upload',
  uploadProfile: 'Upload Area Picture',
  enter: 'Enter',
  exit: 'Exit',
  route: '- - - - - - - - - - - - - - -',
  cardNumber: 'Card Number',
  loginSuccess: 'Login Successful',
  emailSent: 'Email is sent to your email address',
  back: 'Back',
  successfullyRegistered: 'User registered successfully',
  AllList: 'All List',
  latitudeOfArea: 'Latitude of the area',
  longitudeOfArea: 'Longitude of the area',
  spaceName: 'Name of Parking Area',
  noOfRows: 'No of Rows',
  noOfLots: 'Total Parking slots',
  spaceDetails: 'Space Details',
  accepted: 'Accepted',
  addSpace: 'Add Space',
  details: 'Details',
  rejected: 'Rejected',
  requests: 'Requests',
  bookingRequests: 'Booking Requests',
  total: 'Total',
  accept: 'Accept',
  decline: 'Decline',
  jazzCash: 'Jazz Cash',
  easyPaisa: 'Easy Paisa',
  View: 'View Details',
  parkingDetails: 'Parking Details',
  parkingTimer: 'Parking Timer',
  slotID: 'Slot ID',
  extraCharges: 'Extra Charges',
  time: 'Time',
  date: 'Date',
  address: 'Address',
  price: 'Price',
  parkingArea: 'Parking area',
  confirm: 'Confirm',
  cancel: 'Cancel',
  upcoming: 'Upcoming',
  past: 'Past',
  occupied: 'Occupied',
  entryPoint: 'Entry Point',
  exitPoint: 'Exit Point',
  recentPlaces: 'Recent Places',
  popularLocations: 'Popular Parking areas',
  confirmBooking: 'Confirm Booking',
  payPal: 'PayPal',
  location: 'Location',
  stripe: 'Stripe',
  GooglePay: 'Google Pay',
  choosePayMethod: 'Choose Payment Method',
  logout: 'Logout',
  notification: 'Notifications',
  payment: 'Payment',
  personalInfo: 'Personal Information',
  profile: 'My Profile',
  feedbackPlaceholder: 'Share your thoughts and experiences here...',
  feedbackQues: 'How was your experience?',
  Feeback: 'Feedback',
  pickSpot: 'Pick Parking spot',
  Submit: '  Submit  ',
  feedbackSubHeading: 'Your feedback will help us improve our services',
  paymentSuccessMsg: 'Parking booking at parsley was successfully done',
  paymentSuccessful: 'Payment Successful',
  addFeedback: 'Add Feedback',
  VehicleName: 'Vehicle Name',
  licenseNo: 'License No',
  carModel: 'Car Model',
  VehicleDetails: 'Vehicle Details',
  didntRecieveCode: "Didn't recieve code?",
  lastName: 'Last Name',
  sendCode: 'Send OTP',
  verify: 'Verify',
  save: 'Save',
  newPass: 'New Password',
  createNewPass: 'Create New Password',
  resendCode: 'Resend code',
  resendCodein: 'Resend code in',
  createYourNewPass: 'Create New Password for your account',
  email: 'Email',
  password: 'Password',
  continue: 'Continue',
  enterEmail: 'Enter email address',
  confirmPassword: 'Confirm Password',
  login: 'Login',
  register: 'Register',
  forgotPassword: 'Forgot Password',
  title: 'E-PARKING MANAGEMENT',
  welcomeTo: 'Welcome to',
  contiueWith: 'or continue with',
  verifyEmail: 'Verify Your Email',
  user: 'User',
  vendor: 'Vendor',
  CreateAccount: 'Create your',
  loginAccount: 'Login to your',
  forgotPassDetails:
    'Please enter your email address to recieve verification code',
  account: 'Account',
  confirmPass: 'Confirm Password',
  dontHaveAccount: "Don't have an account?",
  signup: 'Sign Up',
  haveAccount: 'Already have an account?',
  signin: 'Sign in',
  phonePlaceholder: '3456999 9',
  rememberMe: 'Remember me',
  next: 'Next',
  skip: 'Skip',
  appIntro:
    'Effortless parking solutions, streamline your experience with our user-friendly E-parking management system today!',
  oneHour: '1 Hour',
  twoHours: '2 Hours',
  threeHours: '3 Hours',
  fourHours: '4 Hours',
  fiveHours: '5 Hours',
  sixHours: '6 Hours',
  bookingSuccess: 'Your booking request has been sent',
};
